### ISSUE TITLE
I not able to receive a call when app is close

### ISSUE THREAD

**Issue by Aritesh** [cybex-dev/twilio_voice#74] opened 2022-01-27 15:53 UTC
hi 
 I not able to receive a call when app is close i tried all things but not working, getting call notification but I can't receiving a call please guide me how to fix this issue

**Comment by ajay-drodify** [comment] 2022-01-28 07:49
same here android app is just stopped when the app is close

**Comment by diegogarciar** [comment] 2022-02-02 05:00
Closing this as duplicate of #17.

**Closed as completed by diegogarciar** 2022-02-02 05:00 UTC
