### ISSUE TITLE
FOREGROUND answering call

### ISSUE THREAD

**Issue by Erchil66** [cybex-dev/twilio_voice#113] opened 2023-03-03 02:51 UTC
Is there other way for me to open the app when answering in foreground which is fully terminate the app, When i tried to answer the call is just no activity screen showing after accepting the answer call and i tried to fork it, And comment the` hasStarted = true` and now its showing the native background activity.

also when in call by the way the mute/unmute doesn't work either for both background or in app answering call.

can someone help me this.

![image](https://user-images.githubusercontent.com/92772509/222618838-47b006ac-166a-404c-9463-0e0a4208a7df.png)

**Comment by cybex-dev** [comment] 2023-04-06 18:39
@Erchil66 if I understand correctly, you want to open your app from the native call screen?

I'm not following exactly what the problem is. Could you provide some steps to replicate or what you see for the problem to show itself?

**Comment by cybex-dev** [comment] 2023-04-14 06:14
@Erchil66 following up for an update.

**Comment by Erchil66** [comment] 2023-05-07 16:35
@cybex-dev hello sorry for late reply i was bit occupied i fork the project ang tweak something on android side

1. Try to terminate the app
2. Recieve call then native android app will show but at some point the mute and speaker won’t actually work even though the callInvite is not null.
3. Now i want to achieve is when on foreground i want to open my app, It work actually when you put true on the hasStarted then on the notification side set to open app by calling it’s package name,But at some point still mute and speaker wont work and the listener on call status connected wont trigger either the callActive with incomingStatus,But still you can hear the person who called you, The call was commited and working fine, It’s Specifically no ui able to show and cant assess what to do next.Need Help
4. This is actually happen on android 12 below and also for xiami phones on android.
5. Question:  Am quite lost sometime when on terminate some phones the call came on notification and other is showing the native call while the app is terminate, Thus should notification above like answer and end only applicable when phone is lock?

**Comment by cybex-dev** [comment] 2023-05-26 04:33
@Erchil66 thanks for the feedback, I don't entirely follow but I will check out Android specifically (answering from closed state and opened/running state).

**Comment by cybex-dev** [comment] 2023-07-27 23:28
#140

**Comment by cybex-dev** [comment] 2023-07-27 23:29
@Erchil66 this is my most recent experience which I'm addressing, does this sound similar to your problem?

**Comment by cybex-dev** [comment] 2023-08-31 23:12
Check out #151 merged

**Comment by cybex-dev** [comment] 2023-09-15 23:40
See [release 0.1.0](https://pub.dev/packages/twilio_voice/versions/0.1.0)

**Closed as completed by cybex-dev** 2023-09-15 23:40 UTC
