### ISSUE TITLE
Call is not Acceptable in background in Android 9 Infinix hot 8.

### ISSUE THREAD

**Issue by Ahmadgnoor** [cybex-dev/twilio_voice#81] opened 2022-03-18 11:10 UTC
Call is not Acceptable in background in Android 9 Infinix hot 8. and also the Caller go back untill the Calle go to Call screen ..Please check and resolve this issue .... 
Also a request to update to kotline from java in android

**Comment by cybex-dev** [comment] 2023-05-26 04:09
@Ahmadgnoor regarding first issue, could you explain in more detail what the problem is.

For Kotlin conversion request, feel free to submit a PR.

**Comment by cybex-dev** [comment] 2023-07-27 23:43
@Ahmadgnoor I believe I replicated your problem, could you please confirm?
#140

**Comment by Ahmadgnoor** [comment] 2023-07-31 07:32
Yes this issue is still exist

**Comment by cybex-dev** [comment] 2023-08-06 22:46
@Ahmadgnoor thanks for the feedback - just to confirm whether #140 is infact what you're experiencing.

Also, as per your request, I'm in the process of rewriting into Kotlin.

**Comment by cybex-dev** [comment] 2023-08-31 23:13
Check out #151 merged

**Comment by cybex-dev** [comment] 2023-09-15 23:39
@Ahmadgnoor rewritten in Kotlin as requested.
See [release 0.1.0](https://pub.dev/packages/twilio_voice/versions/0.1.0)

**Closed as completed by cybex-dev** 2023-09-15 23:39 UTC
